### ISSUE TITLE
reproducing simulations

### ISSUE THREAD

**Issue by koenvandenberge** [theislab/scCODA_reproducibility#3]
Hi All,

Congratulations on a very nice paper and methodology!

I am attempting to re-use the simulations provided by `scCODA`. I have downloaded the simulated data from Zenodo. There, it is mentioned, that more information is available in the `README.txt` file, however, there is no such file provided on Zenodo. Is it possible this did not get uploaded along with the simulated data and results?

I am particularly interested in interpreting the variables `sccoda_effects` file as well as the `generation_parameters` file.

Thanks in advance for your help.
Koen

**Comment by johannesostner** [comment]
Hi Koen!
I am sorry for this, but the link to zenodo in this repository pointed to an old version of the data. The current one (with a readme file) is under this link: https://zenodo.org/record/5084440#.YkW8UDdBxAc
I'v also updated the links here accordingly.
I hope that this helps you in understanding our benchmarks. If you have any further questions, please feel free to ask again!

**Comment by koenvandenberge** [comment]
Great, thank you for pointing me to the right link!

**Comment by johannesostner** [comment]
Hi @koenvandenberge!

Thanks for pointing this out! To make dealing with the data in zenodo easier, i.e. not having one file per dataset, we combined all generated datasets into one anndata object. I just realized that during this process, datasets with more than 5 cell types were cut off.

When we ran our benchmarks, we did not combine the datasets into one object, this was purely a mistake in the data files on zenodo. Therefore, we did not notice this earlier.

I fixed the bug in the code to combine the datasets, such that all cell types are now saved, and re-uploaded the data. You can find it at https://doi.org/10.5281/zenodo.6473255

Please note that for the way you extracted the datasets in the code above, you will now get some cell types that are NaN in all samples (not all datasets have the same number of cell types, therefore cell types were added to the smaller ones during combination). You should remove these, by running `curData = curData[:, ~(np.all(np.isnan(curData.X), axis=0))]` in Python or an equivalent line in R.

I am very sorry that this mistake slipped through when preparing the reproducibility repository, and hope that this answers your question.

**Comment by koenvandenberge** [comment]
Thanks, it looks like third time's a charm! :)
